### ISSUE TITLE
Can you provide stylegan v3 network of finetuned model?

### ISSUE THREAD

**Issue by endlesswho** [Sxela/stylegan3_blending#1]
the finetuned model /content/drive/MyDrive/00000-stylegan3-t-ffhq-256x256-gpus1-batch16-gamma6.6/network-snapshot-000160.pkl isn't exist. Can you give us a link to your model?

**Comment by Sxela** [comment]
Hi! You need to plug in your own fine-tuned models.

**Comment by endlesswho** [comment]
all right!
