### ISSUE TITLE
Spatial mismatch

### ISSUE THREAD

**Issue by ekolodin** [Sxela/stylegan3_blending#2]
Could you please tell me how do you manage with "spatial mismatch" while making pairs with StyleGAN3? There are no problems with StyleGAN2, because photos are aligned. But in StyleGAN3 there are some options for translation, that's why the images produced by FFHQ StyleGAN3 and Blended StyleGAN3 are not well matched with each other, how do you manage with this problem?

**Comment by Sxela** [comment]
You can realign samples after generating (crop and rotate the images, I mean). But at some point, I've dropped the idea and used Stylegan2 config in Stylegan3 repo.

**Comment by ekolodin** [comment]
Thank you!
